### ISSUE TITLE
[Edit Last.fm Scrobbles]  Language help please

### ISSUE THREAD

**Issue by nicoleahmed** [CennoxX/userscripts#10]
Hi 
This is an excellent script thank you

please could we have instructions for changing away from the German language? I have posted this on your greasy fork page too

Also please could some indication of what the permission "PlaylistLover" is for in the code page? Thanks!

**Comment by nicoleahmed** [comment]
I am trying changing this line window.location.replace("https://www.last.fm/de/api/auth?api_key=" + api_key + "&cb=https://www.last.fm/api");

to

window.location.replace("https://www.last.fm/en/api/auth?api_key=" + api_key + "&cb=https://www.last.fm/api");

**Comment by nicoleahmed** [comment]
just getting rid of de works too

**Comment by CennoxX** [comment]
I've updated the script accordingly and reworded the info about the permission to the Last.fm-application (PlaylistLover) on GreasyFork.
