### ISSUE TITLE
[Edit Last.fm Scrobbles]  trouble with ampersands in edit fields

### ISSUE THREAD

**Issue by nicoleahmed** [CennoxX/userscripts#12]
Hi 
A small issue

Ampersands in fields -e.g. name "Ray Of Sun - Sub Focus & Wilkinson" will not allow edits to be saved

Thanks
Nicole

**Comment by nicoleahmed** [comment]
I've had a look at this - but I am a novice

realised the issue was around uri encoding where there are ampersands involved 

see here: https://stackoverflow.com/questions/5503869/last-fm-api-and-the-character

**Comment by nicoleahmed** [comment]
I had a go at fixing this - seems to be working for me

Added two lines to ScrobbleSong function - L158 and L164 - encoded data and send encoded data

https://github.com/CennoxX/userscripts/pull/13/files#diff-9cda5ac951381d341e8e515a62aad29a5666ce951fad73b8ebe8c0dd4afe75d2R145-R175

**Comment by CennoxX** [comment]
Thank you very much for fixing this bug.

**Comment by nicoleahmed** [comment]
You're welcome - thank you for sharing the script in the first place
