### ISSUE TITLE
[Get label from Fernsehserien.de] scheint keine Funktion zu haben

### ISSUE THREAD

**Issue by LeChatNoir666** [CennoxX/userscripts#3]
Laut Beschreibung müsste ja etwas zu sehen sein, wenn ich auf wikidata eine Serienseite öffne oder habe ich die Beschreibung falsch verstanden?
"This script offers the Fernsehserien.de label based on episode number or title as Wikidata label."

Getestet im FF und Chromium mit diversen Serien wie z.B. "Ein Herz und eine Seele" und "Mit Schirm, Charme und Melone".

**Comment by CennoxX** [comment]
Erklärung zu "Get label from Fernsehserien.de" erweitert, damit hier soweit erledigt.

**Comment by LeChatNoir666** [comment]
Sorry, das ich das nochmal aufmache, aber bei mir ist so etwas nicht zu sehen...

Ich habe auch mal "The Twin Thing" aufgemacht und das Ergebnis ist sowohl im FF als auch im Centbrowser (Chromiumbasierend) folgendes:
![FunztNicht](https://user-images.githubusercontent.com/59604462/140168713-899bcceb-6944-41f4-8963-d40d703feb3b.png)

Aber die Idee von deinem Script ist Klasse und soweit ich sah einzigartig! :)


Apropos Fernsehserien...
Bist du gut im scrapen? :)
Habe da ein Projekt aber ich bin Grottenschlecht im coden...
Und mit Grease/Violentmonkey kenne ich mich nicht so wirklich gut aus...

**Comment by CennoxX** [comment]
@LeChatNoir666: Dein Screenshot war sehr hilfreich, ich habe es nachgeprüft, das Script war bisher nicht sprachunabhängig. Ich habe es soweit angepasst, dass es erstmal in den meisten Fällen funktionieren sollte.

An dem Scraping-Projekt bin ich interessiert, gerne auch per Mail, die E-Mailadresse steht im Script.

**Comment by LeChatNoir666** [comment]
Gerne doch :)
Kurzes Zwischenfazit:
Im Centbrowser funktioniert es nun, im FF mit Violentmonkey hingegen nicht.

Ich schreib dir dann mal ne Mail :)
