### ISSUE TITLE
[Filmografie von IMDb nach Wikipedia] Stopped working

### ISSUE THREAD

**Issue by V-Toll** [CennoxX/userscripts#5]
The script seems to have stopped working.

Tried it in Google Chrome and Firefox with Tampermonkey.

**Comment by CennoxX** [comment]
I fixed that error. There also seems to be some changes in the browser behaviour. Now the website scrolls back and forth at the beginning, I had not noticed that before. I'll take a look at this later. You can stop the scrolling by setting "Number of TV episodes from the same series to display" of "Name pages" to "All" in https://www.imdb.com/preferences/general.
