### ISSUE TITLE
[Filmografie von IMDb nach Wikipedia] Computerspiele in Filmografie erwähnen?

### ISSUE THREAD

**Issue by V-Toll** [CennoxX/userscripts#6]
IMDb listet auch Computerspiele in den Filmografien von Darstellern, etc. auf:
Beispiele:

- https://www.imdb.com/name/nm0001646/
- https://www.imdb.com/name/nm3950075/
- https://www.imdb.com/name/nm0001780/

Im Moment werden diese Einträge nicht vom Skript übernommen. Bewusst? Sollte es die Option geben, diese zu übernehmen?

**Comment by CennoxX** [comment]
Ja, das wird bewusst gemacht/dazu wird es keine Option geben. Computerspiele und Werke die sich noch in Produktion befinden, werden nicht aufgenommen. In Wikipedia werden diese in Filmografien nicht aufgeführt. Wenn Computerspiele aufgenommen werden sollen, kann das selbst im Script angepasst werden.

Dazu die Zeilen 51-55
```javascript
if (creditType.includes('in_production') || creditType.includes('Video Game')){
    return;
}
credit.type = creditType
    .replace(/\(Documentary short\)/, 'Dokumentar-Kurzfilm')
```
ersetzen mit
```javascript
if (creditType.includes('in_production')){
    return;
}
credit.type = creditType
    .replace(/\(Video Game\)/, 'Computerspiel')
    .replace(/\(Documentary short\)/, 'Dokumentar-Kurzfilm')
```
