### ISSUE TITLE
[JSON-LD from IMDb to QuickStatements] 

### ISSUE THREAD

**Issue by backache** [CennoxX/userscripts#7]
This look like a script I could find useful, but despite working in IT I can't work out how, I have installed it via tampermonkey it seems to be working but I can't see a button or whatever to trigger it off, are there some simple instructions somewhere for it?

**Comment by CennoxX** [comment]
Yes, take a look at the [Readme](https://github.com/CennoxX/userscripts#json-ld-from-imdb-to-quickstatements). In short: open [QuickStatements](https://quickstatements.toolforge.org/#/batch), login at QuickStatements, open IMDb sites at other tabs, click on the button Import V1 commands.
