### ISSUE TITLE
Paywall Breaker does not work on echo-online 

### ISSUE THREAD

**Issue by angrest** [CennoxX/userscripts#8]
on echo-online.de, text is still scrambled when using the script.
e.g. https://www.echo-online.de/lokales/darmstadt/bessungens-letzte-echte-metzgerei-macht-zu-2557858

**Comment by CennoxX** [comment]
I've no problems with this page, this migt be a timing issue. I only tested Firefox & Tampermonkey. Do you see the text at your console (F12)? Are there any errors?

**Comment by angrest** [comment]
Works indeed in FF, but does not in Safari - in the console, there is unfortunately no useful information

**Comment by CennoxX** [comment]
Sorry, I only support Firefox and Tampermonkey.
