### ISSUE TITLE
[Paywall Breaker][haz.de] Artikeltext wird nur in der Konsole angezeigt

### ISSUE THREAD

**Issue by chidniu** [CennoxX/userscripts#9]
Hallo, erstmal danke für das Erstellen und Pflegen dieser Userscripte. 

Leider funktioniert der Paywall Breaker aktuell nicht richtig auf haz.de:

![screenshot](https://github.com/CennoxX/userscripts/assets/5339604/6264b29a-fc66-4799-ad8e-2becd00c7553)

![console](https://github.com/CennoxX/userscripts/assets/5339604/26407cf0-ad7c-4412-aaf0-15b346e75ba6)

Das ist unter Firefox 113.0.1 (Linux) mit Violentmonkey 2.14.0.

**Comment by CennoxX** [comment]
Sorry, I only support Firefox and Tampermonkey.

**Comment by chidniu** [comment]
A quick hint for everyone who might be having the same problem: Violentmonkey seems to handle loading of the script differently: It runs before all the elements are loaded. Even `@run-at document-idle` doesn't help for some reason. The brute force method works perfectly though. Wrapping the whole code in a `setTimeOut` call:

```
// ==UserScript==
[...]
// ==/UserScript==
/* jshint esversion: 11 */
/* eslint quotes: ["warn", "double", {"avoidEscape": true}] */
/* eslint curly: "off" */

setTimeout(function() {
        (async function() {
        "use strict";
        var url,site,html,parser,htmlDoc,articleText,jsonText,jsonObj,locationText;
[...]
        };
    })();
}, 2000);
